### POST request to create a patient
POST http://localhost:4001/patients
Content-Type: application/json

{
  "name": "Roy Mukherjee",
  "email": "roy@gmail.com",
  "address": "12/2 MG Road",
  "dateOfBirth": "2001-01-11",
  "registeredDate": "2026-01-09"
}

###