### POST request to create a patient
POST http://localhost:4001/patients
Content-Type: application/json

{
  "name": "Wolf Reed",
  "email": "swolf@gmail.com",
  "address": "112 main st",
  "dateOfBirth": "1989-07-12",
  "registeredDate": "2025-11-12"
}

###